import io.mehow.laboratory.gradle.DependencyContribution

plugins {
  id "org.jetbrains.kotlin.jvm"
  id "io.mehow.laboratory"
}

laboratory {
  featureFactory()
  featureSourceFactory()
  sourcedStorage()
  optionFactory()

  dependency(project(":feature"), [DependencyContribution.FeatureSourceFactory])
}
