// Code generated by Wire protocol buffer compiler, do not edit.
// Source: io.mehow.laboratory.datastore.StorageData in
// io/mehow/laboratory/datastore/storage_data.proto
@file:Suppress("DEPRECATION", "RUNTIME_ANNOTATION_NOT_SUPPORTED")

package io.mehow.laboratory.datastore

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

public class StorageData(
  strings: Map<String, String> = emptyMap(),
  booleans: Map<String, Boolean> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<StorageData, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 0,
  )
  public val strings: Map<String, String> = immutableCopyOf("strings", strings)

  @field:WireField(
    tag = 2,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    schemaIndex = 1,
  )
  public val booleans: Map<String, Boolean> = immutableCopyOf("booleans", booleans)

  @Deprecated(message = "Shouldn't be used in Kotlin", level = DeprecationLevel.HIDDEN)
  override fun newBuilder(): Nothing =
    throw AssertionError(
      "Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin"
    )

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StorageData) return false
    if (unknownFields != other.unknownFields) return false
    if (strings != other.strings) return false
    if (booleans != other.booleans) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + strings.hashCode()
      result = result * 37 + booleans.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (strings.isNotEmpty()) result += """strings=$strings"""
    if (booleans.isNotEmpty()) result += """booleans=$booleans"""
    return result.joinToString(prefix = "StorageData{", separator = ", ", postfix = "}")
  }

  public fun copy(
    strings: Map<String, String> = this.strings,
    booleans: Map<String, Boolean> = this.booleans,
    unknownFields: ByteString = this.unknownFields,
  ): StorageData = StorageData(strings, booleans, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<StorageData> =
      object :
        ProtoAdapter<StorageData>(
          FieldEncoding.LENGTH_DELIMITED,
          StorageData::class,
          "type.googleapis.com/io.mehow.laboratory.datastore.StorageData",
          PROTO_3,
          null,
          "io/mehow/laboratory/datastore/storage_data.proto",
        ) {
        private val stringsAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING)
        }

        private val booleansAdapter: ProtoAdapter<Map<String, Boolean>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.BOOL)
        }

        override fun encodedSize(`value`: StorageData): Int {
          var size = value.unknownFields.size
          size += stringsAdapter.encodedSizeWithTag(1, value.strings)
          size += booleansAdapter.encodedSizeWithTag(2, value.booleans)
          return size
        }

        override fun encode(writer: ProtoWriter, `value`: StorageData) {
          stringsAdapter.encodeWithTag(writer, 1, value.strings)
          booleansAdapter.encodeWithTag(writer, 2, value.booleans)
          writer.writeBytes(value.unknownFields)
        }

        override fun encode(writer: ReverseProtoWriter, `value`: StorageData) {
          writer.writeBytes(value.unknownFields)
          booleansAdapter.encodeWithTag(writer, 2, value.booleans)
          stringsAdapter.encodeWithTag(writer, 1, value.strings)
        }

        override fun decode(reader: ProtoReader): StorageData {
          val strings = mutableMapOf<String, String>()
          val booleans = mutableMapOf<String, Boolean>()
          val unknownFields =
            reader.forEachTag { tag ->
              when (tag) {
                1 -> strings.putAll(stringsAdapter.decode(reader))
                2 -> booleans.putAll(booleansAdapter.decode(reader))
                else -> reader.readUnknownField(tag)
              }
            }
          return StorageData(strings = strings, booleans = booleans, unknownFields = unknownFields)
        }

        override fun redact(`value`: StorageData): StorageData =
          value.copy(unknownFields = ByteString.EMPTY)
      }

    private const val serialVersionUID: Long = 0L
  }
}
