include(":samples:basic")
include(":samples:default-option")
include(":samples:multi-module")
include(":samples:multi-module:multi-module-a")
include(":samples:multi-module:multi-module-b")
include(":samples:multi-module:multi-module-c")
include(":samples:firebase")
include(":samples:supervision")
include(":samples:ci-check")

includeBuild("library")
