include(":library:laboratory")
include(":library:shared-preferences")
include(":library:inspector")
include(":library:hyperion-plugin")
include(":library:generator")
include(":library:gradle-plugin")
include(":library:data-store")

include(":sample")
include(":sample:module-a")
include(":sample:module-b")
include(":sample:module-c")
