[versions]
agp = "9.1.0"
android-material = "1.13.0"
androidx-appcompat = "1.7.1"
androidx-datastore = "1.2.1"
androidx-fragment = "1.8.9"
androidx-recyclerview = "1.4.0"
androidx-viewmodel = "2.10.0"
androidx-viewpager2 = "1.1.0"
auto-service-ksp = "1.2.0"
binary-compatibility-validator = "0.18.1"
buildconfig = "6.0.9"
dokka = "2.2.0"
hyperion = "0.9.38"
junit = "4.13.2"
kotest = "6.1.10"
kotlin = "2.3.10"
kotlinpoet = "2.3.0"
kotlinx-coroutines = "1.10.2"
ksp = "2.3.6"
ktfmt = "0.62"
maven-publish = "0.36.0"
robolectric = "4.16.1"
spotless = "8.4.0"
tapmoc = "0.4.1"
turbine = "1.2.1"
wire = "6.2.0"

# Used by convention plugin
jvm-target = "11"
android-min-sdk = "23"
android-compile-sdk = "36"

[plugins]
agp-application = { id = "com.android.application", version.ref = "agp" }
agp-library = { id = "com.android.library", version.ref = "agp" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
laboratory-convention = { id = "io.mehow.laboratory.convention" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
# Used by convention plugin
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
wire = { id = "com.squareup.wire", version.ref = "wire" }

[libraries]
android-material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-core", version.ref = "androidx-datastore" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
androidx-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-viewmodel" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "androidx-viewpager2" }
auto-service-ksp = { group = "dev.zacsweers.autoservice", name = "auto-service-ksp", version.ref = "auto-service-ksp" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
hyperion-core = { group = "com.willowtreeapps.hyperion", name = "hyperion-core", version.ref = "hyperion" }
hyperion-plugin = { group = "com.willowtreeapps.hyperion", name = "hyperion-plugin", version.ref = "hyperion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
# Included to be picked up by dependencies update automation
ktfmt = { group = "com.facebook", name = "ktfmt", version.ref = "ktfmt" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
wire = { group = "com.squareup.wire", name = "wire-runtime", version.ref = "wire" }

gradle-agp = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
gradle-agp-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
gradle-kgp = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kgp-api = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin-api", version.ref = "kotlin" }
gradle-maven-publish = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "maven-publish" }
gradle-spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
gradle-tapmoc = { group = "com.gradleup.tapmoc", name = "tapmoc-gradle-plugin", version.ref = "tapmoc" }
