name: Gradle Wrapper Validation
on:
  workflow_call:

jobs:
  gradle_wrapper_validation:
    if: ${{ github.repository == 'MiSikora/laboratory' }}
    name: Gradle Wrapper Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Set Up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: zulu
          java-version: 21

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5.0.2
