name: Gradle wrapper validation
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
