name: Gradle Wrapper Validation
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate-gradle-wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
