name: Release
on:
  push:
    tags:
      - '*.*.*'

defaults:
  run:
    working-directory: library

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache Gradle Dirs
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-
      - name: Deploy Release
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_SIGNING_KEY: ${{ secrets.SONATYPE_NEXUS_SIGNING_KEY }}
        run: ./gradlew uploadArchives --no-daemon --no-parallel --stacktrace
      - name: Stop Gradle
        run: ./gradlew --stop

  github-release:
    name: Github Release
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Extract Release Notes
        id: release-notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release-notes.outputs.release-notes }}
          files: |
            /*/build/**/*.aar
            /*/build/**/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
