name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

jobs:
  quality_check:
    name: Quality Check
    uses: ./.github/workflows/quality_check.yml

  publish-release:
    if: ${{ github.repository == 'MiSikora/laboratory' }}
    name: Publish Release
    runs-on: ubuntu-latest
    needs: quality_check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Set Up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Gradle Directories
        uses: actions/cache@v6.1.0
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Deploy Release
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SONATYPE_NEXUS_SIGNING_KEY }}
        run: ./gradlew publish --no-configuration-cache --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop

      - name: Extract Release Notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v3.1.0
        with:
          changelog_file: ./docs/changelog.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3.0.0
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: |
            ./library/*/build/outputs/aar/*.aar
            ./library/*/build/libs/!(*-sources|*-javadoc).jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
