name: Snapshot
on:
  workflow_dispatch:
  push:
    branches:
      - trunk

jobs:
  publish-snapshot:
    if: ${{ github.repository == 'MiSikora/laboratory' }}
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout Repo
        uses: actions/checkout@v6.0.0

      - name: Configure JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Gradle Dirs
        uses: actions/cache@v4.3.0
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Deploy Snapshot
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        run: ./gradlew publish --stacktrace

      - name: Build HTML Docs
        run: ./gradlew dokkaHtmlMultiModule --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop

      - name: Publish Website
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          CONFIG_FILE: ./mkdocs.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: ./docs/requirements.txt
