name: Quality Check
on:
  push:
    branches:
      - trunk
    paths-ignore:
      - 'library/docs/**'
      - '**.md'
      - '.github/CODEOWNERS'
  pull_request:
    paths-ignore:
      - 'library/docs/**'
      - '**.md'
      - '.github/CODEOWNERS'

jobs:
  tests:
    if: ${{ github.repository == 'MiSikora/laboratory' }}
    name: JVM Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6.0.1

      - name: Configure JDK
        uses: actions/setup-java@v5.1.0
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Gradle Dirs
        uses: actions/cache@v5.0.1
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Run Tests
        run: ./gradlew test --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop

  spotless:
    if: ${{ github.repository == 'MiSikora/laboratory' }}
    name: Spotless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6.0.1

      - name: Configure JDK
        uses: actions/setup-java@v5.1.0
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Gradle Dirs
        uses: actions/cache@v5.0.1
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Run Spotless
        run: ./gradlew spotlessCheck --stacktrace

      - name: Run Samples Spotless
        working-directory: ./samples
        run: ./gradlew spotlessCheck

      - name: Stop Gradle
        run: ./gradlew --stop

  lint:
    if: ${{ github.repository == 'MiSikora/laboratory' }}
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6.0.1

      - name: Configure JDK
        uses: actions/setup-java@v5.1.0
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Gradle Dirs
        uses: actions/cache@v5.0.1
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Run Lint
        run: ./gradlew lint --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop

  binary-compatibility:
    if: ${{ github.repository == 'MiSikora/laboratory' }}
    name: Binary compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6.0.1

      - name: Configure JDK
        uses: actions/setup-java@v5.1.0
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Gradle Dirs
        uses: actions/cache@v5.0.1
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Check ABI
        run: ./gradlew apiCheck --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop
