name: Quality Check
on:
  workflow_call:
  pull_request:
    paths-ignore:
      - "library/docs/**"
      - "**.md"
      - ".github/CODEOWNERS"

jobs:
  gradle_wrapper_validation:
    name: Gradle Wrapper Validation
    uses: ./.github/workflows/gradle_wrapper_validation.yml

  tests:
    if: ${{ github.repository == 'MiSikora/laboratory' }}
    name: JVM Tests
    runs-on: ubuntu-latest
    needs: gradle_wrapper_validation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Set Up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Gradle Directories
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Run Tests
        run: ./gradlew test --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop

  spotless:
    if: ${{ github.repository == 'MiSikora/laboratory' }}
    name: Spotless Check
    runs-on: ubuntu-latest
    needs: gradle_wrapper_validation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Set Up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Gradle Directories
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck --stacktrace

      - name: Run Samples Spotless Check
        working-directory: ./samples
        run: ./gradlew spotlessCheck

      - name: Stop Gradle
        run: ./gradlew --stop

  lint:
    if: ${{ github.repository == 'MiSikora/laboratory' }}
    name: Android Lint
    runs-on: ubuntu-latest
    needs: gradle_wrapper_validation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Set Up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Gradle Directories
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Run Lint
        run: ./gradlew lint --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop

  binary-compatibility:
    if: ${{ github.repository == 'MiSikora/laboratory' }}
    name: Binary Compatibility
    runs-on: ubuntu-latest
    needs: gradle_wrapper_validation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Set Up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Gradle Directories
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Check ABI
        run: ./gradlew apiCheck --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop
